
project_id = "htxczdhdospkxjesvztw"

[storage]
[storage.baby_images]
public = true
allowed_mime_types = ["image/jpeg", "image/png", "image/gif", "image/webp", "video/mp4", "video/quicktime"]
file_size_limit = "104857600"
