// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htxczdhdospkxjesvztw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0eGN6ZGhkb3Nwa3hqZXN2enR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzM2MDIsImV4cCI6MjA2MTkwOTYwMn0.dgcsjo3XdaQWTVpKyz1MhbsD3S7pjLWwOI4tbaEKEnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);